[theme]
base = "light"
primaryColor = "#DC2626"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FAFAFA"
textColor = "#09090B"
font = "sans serif"

[server]
headless = false
runOnSave = true

[browser]
gatherUsageStats = false
